### ISSUE TITLE
Error: ENOENT: no such file or directory, open 'test.textbundle/text.markdown'

### ISSUE THREAD

**Issue by zenminimalist** [gonejack/textbundle-to-html#1]
Hi,

I'm getting the following error when trying to use your code:
```
user@MacBook-Air-M1 textbundle-to-html-main % textbundle-to-html test.textbundle
node:fs:599
  handleErrorFromBinding(ctx);
  ^

Error: ENOENT: no such file or directory, open 'test.textbundle/text.markdown'
    at Object.openSync (node:fs:599:3)
    at Object.readFileSync (node:fs:467:35)
    at bundle (file:///opt/homebrew/lib/node_modules/textbundle-to-html/src/bundle.js:11:20)
    at Command.<anonymous> (file:///opt/homebrew/lib/node_modules/textbundle-to-html/src/build.js:21:2)
    at Command.listener [as _actionHandler] (/opt/homebrew/lib/node_modules/textbundle-to-html/node_modules/commander/lib/command.js:488:17)
    at /opt/homebrew/lib/node_modules/textbundle-to-html/node_modules/commander/lib/command.js:1227:65
    at Command._chainOrCall (/opt/homebrew/lib/node_modules/textbundle-to-html/node_modules/commander/lib/command.js:1144:12)
    at Command._parseCommand (/opt/homebrew/lib/node_modules/textbundle-to-html/node_modules/commander/lib/command.js:1227:27)
    at Command.parse (/opt/homebrew/lib/node_modules/textbundle-to-html/node_modules/commander/lib/command.js:897:10)
    at file:///opt/homebrew/lib/node_modules/textbundle-to-html/src/build.js:23:2 {
  errno: -2,
  syscall: 'open',
  code: 'ENOENT',
  path: 'test.textbundle/text.markdown'
}

Node.js v18.4.0

```
Any ideas what the issue is or what I'm issing (not a dev)? I also tried `textbundle-to-html *.textbundle ` as well, same issue,

**Comment by gonejack** [comment]
Hi, @zenminimalist 

Since this tool is a golang project instead of Node.js this issue should belongs to https://github.com/rexgarland/textbundle-to-html
